"""add_unlimit_card_integration

Revision ID: b0b84a2b1251
Revises: c52fe5f167f8
Create Date: 2025-09-22 08:13:55.645250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b84a2b1251'
down_revision: Union[str, None] = 'c52fe5f167f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unlimit_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unlimit_webhooks_webhook_id'), 'unlimit_webhooks', ['webhook_id'], unique=True)
    op.create_table('unlimit_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('unlimit_card_id', sa.String(length=100), nullable=False),
    sa.Column('unlimit_user_id', sa.String(length=100), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('card_status', sa.String(length=20), nullable=True),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('expiry_month', sa.Integer(), nullable=True),
    sa.Column('expiry_year', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('region', sa.String(length=5), nullable=False),
    sa.Column('card_program', sa.String(length=50), nullable=True),
    sa.Column('spending_limits', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unlimit_cards_unlimit_card_id'), 'unlimit_cards', ['unlimit_card_id'], unique=True)
    op.create_index(op.f('ix_unlimit_cards_unlimit_user_id'), 'unlimit_cards', ['unlimit_user_id'], unique=False)
    op.create_table('unlimit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('unlimit_transaction_id', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('merchant_category', sa.String(length=10), nullable=True),
    sa.Column('transaction_status', sa.String(length=20), nullable=False),
    sa.Column('decline_reason', sa.String(length=100), nullable=True),
    sa.Column('auth_code', sa.String(length=20), nullable=True),
    sa.Column('wallet_balance_before', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('wallet_balance_after', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('processing_fee', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['unlimit_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unlimit_transactions_unlimit_transaction_id'), 'unlimit_transactions', ['unlimit_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unlimit_transactions_unlimit_transaction_id'), table_name='unlimit_transactions')
    op.drop_table('unlimit_transactions')
    op.drop_index(op.f('ix_unlimit_cards_unlimit_user_id'), table_name='unlimit_cards')
    op.drop_index(op.f('ix_unlimit_cards_unlimit_card_id'), table_name='unlimit_cards')
    op.drop_table('unlimit_cards')
    op.drop_index(op.f('ix_unlimit_webhooks_webhook_id'), table_name='unlimit_webhooks')
    op.drop_table('unlimit_webhooks')
    # ### end Alembic commands ###
