"""add_fee_collection_system

Revision ID: bc7cdeb0d05d
Revises: b0b84a2b1251
Create Date: 2025-09-22 10:16:40.504134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7cdeb0d05d'
down_revision: Union[str, None] = 'b0b84a2b1251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_withdrawals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('currency_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('destination_address', sa.String(length=66), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('withdrawal_reason', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('currency_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('revenue_wallet_address', sa.String(length=66), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('fee_amount', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('transactions', sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('fee_collected', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('revenue_wallet_address', sa.String(length=66), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'revenue_wallet_address')
    op.drop_column('transactions', 'fee_collected')
    op.drop_column('transactions', 'fee_percentage')
    op.drop_column('transactions', 'fee_amount')
    op.drop_table('fee_collections')
    op.drop_table('fee_withdrawals')
    # ### end Alembic commands ###
