"""Add custodial wallet fields

Revision ID: c52fe5f167f8
Revises: b6efd106736e
Create Date: 2025-09-20 18:08:45.127703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52fe5f167f8'
down_revision: Union[str, None] = 'b6efd106736e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_custodial', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('encrypted_private_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('wallet_exported', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_exported')
    op.drop_column('users', 'encrypted_private_key')
    op.drop_column('users', 'is_custodial')
    # ### end Alembic commands ###
